apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-project-deployment
  labels:
    app  : falcon-k8s-application 
spec:
  selector:
    matchLabels:
      project: falcon-project
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        project: falkon-project
    spec:
      containers:
        - name : falkon-project-webapp
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: falcon-autoscaling-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta2v2
    kind: Deployment
    name: falkon-project-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: 80
        
