apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hosts
  namespace: staging
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "falcon-cluster-ip"
spec:
  rules:
  - host: falcon.tonguru.com
    http:
      paths:
      - backend:
          serviceName: falcon-webapp-service
          servicePort: 80

  - host: httpd.falcon.tonguru.com
    http:
      paths:
      - backend:
          serviceName: httpd
          servicePort: 80

  - host: nginx.falcon.tonguru.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
