apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
  - host: falcon.tonguru.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: falcon-webapp-service
            port:
              number: 80

  - host: web1.falcon.tonguru.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: falcon-webapp-service
            port:
              number: 80

  - host: web2.falcon.tonguru.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: falcon-webapp-service
            port:
              number: 80
