apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: staging
spec:
  acme:
    email: forfalcon@protonmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
       ingress:
         class: nginx
         
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
  namespace: staging
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: falcon.tonguru.com
  dnsNames:
  - falcon.tonguru.com
