apiVersion: v1
kind: Service
metadata:
  name: falcon-webapp-service
  namespace: staging
  labels:
     env  : stage
     owner: Falcon
spec:
  selector:
    project: falcon-project
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
  type: NodePort
