apiVersion: v1
kind: Service
metadata:
  name: falcon-autoscaling-pod-service
  namespace: staging
  labels:
     env  : stage
     owner: Falcon
spec:
  selector:
    project: falcon-project
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Load Balancer
      targetPort: 80  # Pod
  type: LoadBalancer
