#---------------------------------------------------------------------
# GitHub Action workflow to deploy WebApp to GKE
#
# Version      Date        Info
# 1.0          2021        Initial Version
#
# Made by Sergii Sokolov Copyleft (c) 2021
#---------------------------------------------------------------------
name: CICD-Pipeline-to-GKE

on: 
  push:
    branches: 
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    


  cd:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
   
